[Settings]

# Theme
gtk-theme-name=Adwaita-Dark
gtk-application-prefer-dark-theme=1

# Icons
gtk-icon-theme-name=Papirus-Dark

# Cursor
gtk-cursor-theme-name=Adwaita
gtk-cursor-theme-size=0

# Font
gtk-font-name=Adwaita Sans 12

# Toolbar
gtk-toolbar-style=GTK_TOOLBAR_BOTH_HORIZ
gtk-toolbar-icon-size=GTK_ICON_SIZE_LARGE_TOOLBAR

# UI
gtk-button-images=0
gtk-menu-images=0

# Sounds
gtk-enable-event-sounds=1
gtk-enable-input-feedback-sounds=1

# Font rendering
gtk-xft-antialias=1
gtk-xft-hinting=1
gtk-xft-hintstyle=hintmedium